mj:
  discord:
    guild-id: 1046979304547954728
    channel-id: 1063523239718035607
    user-token: MTA5MTUxOTk3ODAxODE4NTMyNg.GNXyVc.QeIK4eOjhVm52PTWKwtvaoIBnpg-2m8Ar4IpJo
    session-id: 67a6b2535f1a0885fe8ae9f906072cb9
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10