mj:
  discord:
    guild-id: 1146652647265402882
    channel-id: 1146652647265402885
    user-token: MTE0MDQ1NjM1Mjk1OTk2NzQwMw.GwiZTB.IWxdiSL029kCONtt8Z3jU_z0z2_VNhpIvE1LfQ
    session-id: 02e1a80f7f09355aa88c6be68c7ce68d
    user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36
  task-store:
    type: in_memory
    timeout: 30d
  translate-way: null
  queue:
    timeout-minutes: 5
    core-size: 3
    queue-size: 10